dist: xenial
language: node_js

node_js:
  - 8

notifications:
  email: false

install:
    - npm install

cache:
  directories:
    - node_modules

script:
    - npm run lint
    - npm run flow
    - npm run test:types
    - npm run test:e2e -- --env phantomjs
    - npm run test:ssr
    - npm run test:weex